import type { Activity, Category, Companion, Place } from "./types";

function adventure(
  id: string,
  title: string,
  description: string,
  duration: number,
  budget: number,
  place: Place,
  categories: Category[],
  materials: string,
  steps: [string, string, string],
  companions: Companion[] = ["solo", "duo", "groupe"],
): Activity {
  return {
    id,
    title,
    description,
    duration,
    budget,
    place,
    categories,
    materials,
    steps,
    companions,
  };
}

export const activities: Activity[] = [
  adventure(
    "photo-couleur",
    "La chasse aux couleurs",
    "Transformez une promenade familière en collection de détails d’une seule couleur.",
    30,
    0,
    "exterieur",
    ["creatif", "decouverte", "mouvement"],
    "Un téléphone ou un appareil photo déjà disponible, des chaussures confortables.",
    [
      "Choisissez une couleur avant de sortir.",
      "Repérez et photographiez cinq détails de cette couleur, sans photographier les passants.",
      "Donnez un titre à votre collection.",
    ],
  ),
  adventure(
    "trait-continu",
    "Un seul trait",
    "Dessinez un objet du quotidien sans jamais lever le crayon. Les détours font partie du dessin.",
    15,
    0,
    "interieur",
    ["creatif", "detente"],
    "Une feuille de récupération, un crayon, un objet à observer.",
    [
      "Posez un objet simple devant vous.",
      "Dessinez son contour en un seul trait pendant deux minutes.",
      "Recommencez en changeant de point de vue, puis gardez votre version préférée.",
    ],
  ),
  adventure(
    "lettre-futur",
    "Cher moi du futur",
    "Écrivez une petite lettre que vous aurez plaisir à retrouver dans quelques mois.",
    15,
    0,
    "interieur",
    ["creatif", "detente"],
    "Du papier et un stylo, ou une application de notes.",
    [
      "Notez la date et une chose qui vous réjouit aujourd’hui.",
      "Racontez un souhait et une question à votre futur vous.",
      "Choisissez une date de relecture et rangez la lettre.",
    ],
    ["solo"],
  ),
  adventure(
    "degustation-aveugle",
    "Les yeux gourmands",
    "Redécouvrez trois aliments de votre placard en les goûtant les yeux fermés, assis à table.",
    15,
    0,
    "interieur",
    ["gourmand", "decouverte"],
    "Trois aliments déjà disponibles et adaptés aux allergies de chacun, des petites assiettes.",
    [
      "Vérifiez ensemble les ingrédients et allergies avant de préparer les portions.",
      "Goûtez chacun votre tour les yeux fermés, sans vous déplacer.",
      "Décrivez les textures et comparez vos impressions.",
    ],
    ["duo", "groupe"],
  ),
  adventure(
    "fenetre",
    "Voyage à la fenêtre",
    "Prenez le temps de regarder une vue que vous ne remarquez plus.",
    15,
    0,
    "interieur",
    ["decouverte", "detente"],
    "Une fenêtre accessible et un carnet ou du papier.",
    [
      "Installez-vous confortablement devant une fenêtre fermée.",
      "Repérez cinq mouvements, quatre couleurs et trois formes.",
      "Écrivez trois lignes sur ce petit paysage.",
    ],
  ),
  adventure(
    "origami",
    "Un bateau en papier",
    "Pliez un petit bateau avec une feuille qui allait finir au recyclage.",
    15,
    0,
    "interieur",
    ["creatif"],
    "Une feuille rectangulaire de récupération.",
    [
      "Pliez la feuille en deux, puis rabattez les coins du pli vers le milieu et relevez les bandes du bas.",
      "Ouvrez le triangle en losange et remontez les pointes du bas pour former un petit triangle.",
      "Ouvrez de nouveau en losange et écartez délicatement les deux pointes du haut.",
    ],
  ),
  adventure(
    "poeme-placard",
    "Poésie de placard",
    "Les mots sur vos emballages deviennent la matière première d’un poème inattendu.",
    15,
    0,
    "interieur",
    ["creatif", "decouverte"],
    "Quelques emballages déjà présents, du papier et un stylo.",
    [
      "Relevez dix mots sur des emballages.",
      "Composez quatre lignes en utilisant au moins six de ces mots.",
      "Lisez votre poème à voix haute et donnez-lui un titre.",
    ],
  ),
  adventure(
    "pause-musicale",
    "Une chanson, rien d’autre",
    "Offrez toute votre attention à un morceau que vous possédez déjà.",
    15,
    0,
    "interieur",
    ["detente", "decouverte"],
    "Un morceau disponible hors ligne et de quoi l’écouter à volume modéré.",
    [
      "Choisissez un morceau et éloignez les distractions.",
      "Écoutez une fois en suivant un seul instrument.",
      "Réécoutez et notez un détail que vous n’aviez jamais remarqué.",
    ],
  ),
  adventure(
    "etirements",
    "La pause qui délasse",
    "Une courte pause pour remettre doucement le corps en mouvement, sans chercher la performance.",
    15,
    0,
    "interieur",
    ["mouvement", "detente"],
    "Une chaise stable et un peu d’espace dégagé.",
    [
      "Asseyez-vous et relâchez les épaules pendant quelques respirations.",
      "Bougez doucement les mains, les chevilles et les épaules, sans douleur.",
      "Marchez tranquillement quelques minutes, ou poursuivez les mouvements assis.",
    ],
  ),
  adventure(
    "danse",
    "Le salon fait sa fête",
    "Transformez votre salon en petite piste de danse le temps de trois chansons.",
    15,
    0,
    "interieur",
    ["mouvement"],
    "Trois morceaux disponibles hors ligne, un lecteur et un espace dégagé.",
    [
      "Écartez les obstacles et choisissez trois morceaux.",
      "Inventez un geste différent pour chaque refrain, assis ou debout.",
      "Terminez par un morceau calme et reprenez votre souffle.",
    ],
  ),
  adventure(
    "autoportrait",
    "Portrait sans miroir",
    "Dessinez-vous de mémoire et laissez votre imagination remplir les blancs.",
    15,
    0,
    "interieur",
    ["creatif"],
    "Du papier et un crayon.",
    [
      "Fermez les yeux quelques instants pour imaginer votre visage.",
      "Dessinez-vous sans miroir ni photo.",
      "Ajoutez trois détails qui racontent votre humeur du jour.",
    ],
  ),
  adventure(
    "musee-poche",
    "Le musée de poche",
    "Donnez une nouvelle importance à trois petits objets ordinaires.",
    15,
    0,
    "interieur",
    ["creatif", "decouverte"],
    "Trois objets personnels, du papier, un stylo et une surface libre.",
    [
      "Choisissez trois objets qui ont une histoire.",
      "Écrivez pour chacun une étiquette comme au musée.",
      "Disposez votre mini-exposition et faites-en la visite.",
    ],
  ),
  adventure(
    "respiration",
    "Quinze minutes de calme",
    "Créez une parenthèse tranquille pour laisser retomber le bruit de la journée.",
    15,
    0,
    "interieur",
    ["detente"],
    "Une assise confortable et un minuteur si vous le souhaitez.",
    [
      "Installez-vous dans une position confortable.",
      "Observez votre respiration naturelle quelques minutes, sans la forcer.",
      "Écoutez les sons autour de vous puis reprenez tranquillement votre journée.",
    ],
  ),
  adventure(
    "histoire-mots",
    "Trois mots, une histoire",
    "Une clé, un nuage, une chaussette : quelques mots suffisent à lancer une fiction.",
    15,
    0,
    "interieur",
    ["creatif"],
    "Du papier et un stylo, ou une application de notes.",
    [
      "Choisissez trois objets visibles et notez leurs noms.",
      "Écrivez une histoire de dix lignes qui les relie.",
      "Trouvez une dernière phrase qui change le sens du récit.",
    ],
  ),
  adventure(
    "lecture-voix",
    "Des pages à voix haute",
    "Savourez autrement une page d’un livre que vous avez déjà.",
    15,
    0,
    "interieur",
    ["detente", "decouverte"],
    "Un livre ou un texte déjà disponible.",
    [
      "Ouvrez un livre à une page qui vous attire.",
      "Lisez lentement le passage à voix haute.",
      "Relisez votre phrase préférée et notez ce qu’elle évoque.",
    ],
  ),
  adventure(
    "textures",
    "Le carnet des textures",
    "Faites apparaître sur le papier les reliefs discrets de votre intérieur.",
    15,
    0,
    "interieur",
    ["creatif", "decouverte"],
    "Une feuille fine et un crayon à papier, des surfaces solides non fragiles.",
    [
      "Choisissez trois surfaces texturées que le frottement ne risque pas d’abîmer.",
      "Posez la feuille dessus et frottez doucement avec le côté de la mine.",
      "Assemblez les empreintes en petit paysage.",
    ],
  ),
  adventure(
    "the",
    "Le rituel de la tasse",
    "Préparez votre boisson habituelle comme si c’était une petite cérémonie.",
    15,
    0,
    "interieur",
    ["gourmand", "detente"],
    "Une boisson déjà disponible, une tasse et le nécessaire pour la préparer.",
    [
      "Choisissez une tasse et préparez votre boisson.",
      "Observez sa couleur et son parfum, puis laissez-la refroidir si nécessaire.",
      "Buvez lentement en laissant votre téléphone de côté.",
    ],
  ),
  adventure(
    "carte-imaginaire",
    "Une île à inventer",
    "Tracez la carte d’une île où tout porte le nom de vos petits bonheurs.",
    30,
    0,
    "interieur",
    ["creatif"],
    "Du papier et des crayons.",
    [
      "Dessinez le contour d’une île et quelques chemins.",
      "Nommez trois lieux avec des choses que vous aimez.",
      "Ajoutez une légende et imaginez votre première escale.",
    ],
  ),
  adventure(
    "collage",
    "Un collage d’humeur",
    "Composez une petite image de votre humeur avec des papiers de récupération.",
    30,
    0,
    "interieur",
    ["creatif", "detente"],
    "Vieux papiers ou magazines, colle déjà disponible, une feuille support.",
    [
      "Choisissez des couleurs et des morceaux de texte qui vous attirent.",
      "Déchirez les papiers et essayez plusieurs compositions.",
      "Collez votre composition préférée et inscrivez la date au dos.",
    ],
  ),
  adventure(
    "souvenirs",
    "Cinq photos, une époque",
    "Revisitez un souvenir en créant un mini-récit à partir de vos propres photos.",
    30,
    0,
    "interieur",
    ["creatif", "detente"],
    "Cinq photos personnelles, sur papier ou déjà enregistrées sur un appareil.",
    [
      "Choisissez cinq photos d’une même période.",
      "Placez-les dans un ordre qui raconte une histoire.",
      "Écrivez une courte légende pour chacune.",
    ],
  ),
  adventure(
    "cabane",
    "La cabane du salon",
    "Retrouvez le plaisir d’un petit refuge construit avec ce que vous avez.",
    30,
    0,
    "interieur",
    ["creatif", "detente"],
    "Un drap, des coussins et des meubles stables ; aucune flamme à proximité.",
    [
      "Choisissez un coin dégagé et des supports stables sans les escalader.",
      "Installez un drap léger et quelques coussins.",
      "Glissez-vous dans votre cabane avec un livre pendant dix minutes.",
    ],
  ),
  adventure(
    "cadavre-exquis",
    "Une histoire à plusieurs",
    "Écrivez ensemble un récit dont personne ne connaît la direction.",
    30,
    0,
    "interieur",
    ["creatif"],
    "Du papier et des stylos.",
    [
      "La première personne écrit deux phrases puis cache la première.",
      "Passez la feuille et ajoutez deux phrases en ne lisant que la dernière.",
      "Dépliez le récit et lisez-le ensemble.",
    ],
    ["duo", "groupe"],
  ),
  adventure(
    "portrait-croise",
    "Portraits croisés",
    "Dessinez-vous mutuellement en regardant davantage la personne que la feuille.",
    15,
    0,
    "interieur",
    ["creatif"],
    "Une feuille et un crayon par personne.",
    [
      "Installez-vous face à face ou en cercle.",
      "Dessinez une autre personne pendant trois minutes sans viser la ressemblance.",
      "Échangez les dessins et ajoutez un titre bienveillant.",
    ],
    ["duo", "groupe"],
  ),
  adventure(
    "quiz-maison",
    "Le quiz des petites choses",
    "Inventez un quiz sur les objets et les habitudes que vous partagez.",
    30,
    0,
    "interieur",
    ["decouverte"],
    "Papier, stylos et objets du quotidien.",
    [
      "Chaque personne invente cinq questions observables dans la pièce.",
      "Posez-les chacun votre tour et laissez le temps de réfléchir.",
      "Vérifiez ensemble les réponses et racontez les anecdotes associées.",
    ],
    ["duo", "groupe"],
  ),
  adventure(
    "dessert-placard",
    "Le dessert improvisé",
    "Composez un dessert froid avec quelques ingrédients que vous avez déjà.",
    30,
    0,
    "interieur",
    ["gourmand", "creatif"],
    "Ingrédients prêts à consommer déjà disponibles, bols et cuillères ; vérifiez les allergies.",
    [
      "Repérez un fruit, une base crémeuse ou un biscuit selon vos réserves.",
      "Préparez de petites couches dans un bol, avec des ingrédients adaptés à chacun.",
      "Goûtez et donnez un nom à votre création.",
    ],
  ),
  adventure(
    "tartines",
    "Le trio de tartines",
    "Faites de trois petites tartines une dégustation maison.",
    30,
    5,
    "interieur",
    ["gourmand", "creatif"],
    "Pain et trois garnitures adaptées aux allergies, couteau et assiette ; achat estimé à 5 € maximum.",
    [
      "Choisissez une garniture simple pour chaque tartine.",
      "Préparez trois petites portions avec des associations différentes.",
      "Goûtez lentement et choisissez votre favorite.",
    ],
  ),
  adventure(
    "pique-nique-salon",
    "Pique-nique au salon",
    "Changez le décor d’un repas simple en l’installant au milieu du salon.",
    60,
    5,
    "interieur",
    ["gourmand", "detente"],
    "Une couverture, de la vaisselle et des ingrédients simples adaptés à chacun ; estimation de 5 € par personne.",
    [
      "Dégagez un coin confortable et étalez une couverture.",
      "Préparez un repas froid facile à partager.",
      "Installez-vous et racontez un lieu où vous aimeriez pique-niquer.",
    ],
  ),
  adventure(
    "pates-maison",
    "Les pâtes prennent forme",
    "Essayez de façonner de petites pâtes à la main, sans machine.",
    120,
    5,
    "interieur",
    ["gourmand", "creatif"],
    "Farine, eau, sel, saladier, plan de travail propre et casserole ; environ 5 € par personne, contient du gluten.",
    [
      "Mélangez progressivement 100 g de farine et environ 50 ml d’eau par personne en une pâte ferme.",
      "Pétrissez, laissez reposer vingt minutes puis façonnez de petites formes régulières.",
      "Faites cuire dans l’eau bouillante et goûtez pour vérifier la cuisson avant de servir.",
    ],
  ),
  adventure(
    "biscuits",
    "Des biscuits tout simples",
    "Préparez une petite fournée et profitez de son parfum pendant qu’elle cuit.",
    60,
    5,
    "interieur",
    ["gourmand"],
    "Four, plaque, papier cuisson, 100 g de farine, 50 g de beurre et 30 g de sucre ; estimation de 5 €, gluten et lait.",
    [
      "Mélangez les ingrédients en une pâte puis formez de petits biscuits.",
      "Faites cuire à 170 °C environ douze à quinze minutes en surveillant la coloration.",
      "Laissez refroidir sur une surface adaptée avant de goûter.",
    ],
  ),
  adventure(
    "herbes",
    "Le petit jardin de cuisine",
    "Installez un pot aromatique et imaginez les repas qu’il pourrait parfumer.",
    30,
    5,
    "interieur",
    ["decouverte", "detente"],
    "Une plante aromatique identifiée comme comestible, son pot, une soucoupe et de l’eau ; budget estimé de 5 €.",
    [
      "Choisissez une place lumineuse adaptée aux indications de la plante.",
      "Installez la soucoupe et vérifiez si la terre a besoin d’eau.",
      "Notez son nom et deux idées de recettes, sans récolter une plante non identifiée.",
    ],
  ),
  adventure(
    "couture",
    "Un bouton retrouve sa place",
    "Réparez un petit détail d’un vêtement et offrez-lui une nouvelle sortie.",
    30,
    0,
    "interieur",
    ["creatif", "detente"],
    "Un vêtement, un bouton, une aiguille, du fil et des ciseaux déjà disponibles.",
    [
      "Choisissez un bouton à refixer et préparez un fil doublé.",
      "Passez plusieurs fois dans le tissu et les trous du bouton en gardant un peu de jeu.",
      "Nouez au dos, coupez le fil et essayez le vêtement.",
    ],
  ),
  adventure(
    "marque-page",
    "Le marque-page maison",
    "Créez un petit compagnon de lecture à partir d’un emballage propre.",
    15,
    0,
    "interieur",
    ["creatif"],
    "Du carton fin de récupération, des ciseaux et un stylo.",
    [
      "Découpez une bande de carton aux coins arrondis.",
      "Dessinez un motif simple sur une face et une phrase sur l’autre.",
      "Glissez-le dans un livre que vous aimeriez reprendre.",
    ],
  ),
  adventure(
    "nature-morte",
    "La nature morte express",
    "Composez une scène avec trois objets et jouez avec la lumière de la pièce.",
    30,
    0,
    "interieur",
    ["creatif", "decouverte"],
    "Trois objets, un tissu et un téléphone ou appareil photo déjà disponible.",
    [
      "Disposez trois objets sur un tissu près d’une fenêtre.",
      "Déplacez-les pour faire varier leurs ombres.",
      "Prenez trois photos et gardez la composition qui vous plaît le plus.",
    ],
  ),
  adventure(
    "ombres",
    "Le théâtre des ombres",
    "Inventez une petite scène avec des silhouettes et une lumière douce.",
    30,
    0,
    "interieur",
    ["creatif"],
    "Une lampe électrique, un mur libre et vos mains ; aucune bougie.",
    [
      "Placez la lampe face au mur sans la couvrir.",
      "Essayez plusieurs silhouettes avec vos mains.",
      "Racontez une histoire de deux minutes avec deux personnages.",
    ],
  ),
  adventure(
    "apprendre-noeud",
    "Un nœud bien pensé",
    "Observez comment une simple boucle peut transformer une ficelle en outil.",
    15,
    0,
    "interieur",
    ["decouverte"],
    "Une ficelle ou un lacet déjà disponible, à garder loin des jeunes enfants.",
    [
      "Formez une boucle et passez le bout dedans pour un nœud simple.",
      "Essayez ensuite de doubler le passage et comparez les formes.",
      "Dessinez vos essais ; ces nœuds ne servent pas à assurer une personne ou une charge.",
    ],
  ),
  adventure(
    "marche-sons",
    "La balade qui s’écoute",
    "Suivez les sons de votre quartier pendant une courte promenade, en restant attentif à la circulation.",
    15,
    0,
    "exterieur",
    ["decouverte", "detente", "mouvement"],
    "Des chaussures adaptées ; aucun casque nécessaire.",
    [
      "Choisissez un trajet proche et accessible.",
      "Repérez cinq sons différents en marchant tranquillement.",
      "Arrêtez-vous dans un endroit sûr et essayez de les nommer de mémoire.",
    ],
  ),
  adventure(
    "nuages",
    "Le cinéma des nuages",
    "Laissez le ciel vous proposer des formes et des histoires.",
    15,
    0,
    "exterieur",
    ["detente", "creatif"],
    "Une assise extérieure sûre et une tenue adaptée à la météo.",
    [
      "Trouvez un endroit où observer le ciel sans regarder directement le soleil.",
      "Choisissez un nuage et imaginez ce qu’il pourrait représenter.",
      "Observez sa transformation puis inventez un titre à cette scène.",
    ],
  ),
  adventure(
    "alphabet-rue",
    "L’alphabet de la rue",
    "Cherchez des lettres cachées dans les formes du quotidien.",
    30,
    0,
    "exterieur",
    ["decouverte", "creatif", "mouvement"],
    "Un carnet et un crayon, ou un téléphone déjà disponible.",
    [
      "Choisissez cinq lettres de l’alphabet.",
      "Repérez leurs formes dans les branches, les grilles ou les façades depuis les espaces publics.",
      "Notez ou dessinez vos trouvailles pour composer un mot.",
    ],
  ),
  adventure(
    "banc",
    "Le banc des observations",
    "Faites une vraie pause sur un banc, avec pour seule mission de remarquer les détails.",
    15,
    0,
    "exterieur",
    ["detente", "decouverte"],
    "Une assise publique accessible et une tenue adaptée.",
    [
      "Rejoignez un endroit proche où vous pouvez vous asseoir.",
      "Remarquez trois détails du paysage sans observer les personnes avec insistance.",
      "Choisissez un détail à raconter en rentrant.",
    ],
  ),
  adventure(
    "parcours-formes",
    "Le détour géométrique",
    "Un cercle, un triangle, un carré : changez votre regard sur un trajet ordinaire.",
    30,
    0,
    "exterieur",
    ["decouverte", "mouvement"],
    "Des chaussures confortables et éventuellement un carnet.",
    [
      "Définissez un petit trajet aller-retour.",
      "Cherchez trois exemples de chaque forme dans l’environnement.",
      "Revenez par un passage public différent si le temps le permet.",
    ],
  ),
  adventure(
    "croquis-arbre",
    "Le portrait d’un arbre",
    "Dessinez un arbre en vous intéressant à sa silhouette plutôt qu’à chaque feuille.",
    30,
    0,
    "exterieur",
    ["creatif", "detente"],
    "Une feuille, un crayon et un support rigide.",
    [
      "Choisissez un arbre visible depuis un lieu accessible.",
      "Dessinez le tronc et les grandes masses de son feuillage.",
      "Ajoutez trois détails caractéristiques sans prélever de feuilles.",
    ],
  ),
  adventure(
    "balade-sans-photo",
    "Garder les yeux ouverts",
    "Une promenade sans photo, pour collectionner des souvenirs autrement.",
    60,
    0,
    "exterieur",
    ["mouvement", "detente", "decouverte"],
    "Des chaussures adaptées, de l’eau et un trajet connu.",
    [
      "Choisissez un itinéraire adapté à votre mobilité et gardez le téléphone rangé.",
      "Faites trois pauses pour mémoriser un détail visuel.",
      "Au retour, décrivez les trois détails dans un carnet ou à voix haute.",
    ],
  ),
  adventure(
    "pique-nique",
    "Une nappe dehors",
    "Emportez un repas simple dans un espace extérieur autorisé près de chez vous.",
    60,
    5,
    "exterieur",
    ["gourmand", "detente"],
    "Repas froid adapté aux allergies, eau, couverture et sac à déchets ; estimation de 5 € par personne.",
    [
      "Préparez un repas transportable en respectant sa conservation.",
      "Choisissez un lieu proche, autorisé et adapté à la météo.",
      "Profitez du repas puis remportez tous vos déchets.",
    ],
  ),
  adventure(
    "gouter-dehors",
    "Le goûter au grand air",
    "Changez d’horizon le temps d’un goûter tout simple.",
    30,
    5,
    "exterieur",
    ["gourmand", "detente"],
    "Un goûter adapté à chacun, de l’eau et une serviette ; budget estimé de 5 €.",
    [
      "Préparez une petite portion facile à transporter.",
      "Installez-vous dans un endroit proche où manger est autorisé.",
      "Goûtez tranquillement puis laissez la place propre.",
    ],
  ),
  adventure(
    "balade-architecture",
    "Les façades racontent",
    "Repérez les détails architecturaux qui donnent une personnalité à votre quartier.",
    60,
    0,
    "exterieur",
    ["decouverte", "mouvement"],
    "Des chaussures adaptées et un carnet ou téléphone.",
    [
      "Choisissez deux ou trois rues accessibles à proximité.",
      "Cherchez un balcon, une porte et un motif qui vous plaisent, depuis l’espace public.",
      "Dessinez ou décrivez votre détail préféré sans entrer dans les propriétés.",
    ],
  ),
  adventure(
    "pas-ensemble",
    "Une balade, une question",
    "Marchez ensemble autour d’une question légère que vous n’avez jamais pris le temps de poser.",
    30,
    0,
    "exterieur",
    ["mouvement", "detente"],
    "Des chaussures confortables et un trajet accessible à tous.",
    [
      "Choisissez une question, par exemple votre meilleur souvenir de vacances.",
      "Marchez en laissant chaque personne raconter à son rythme.",
      "Terminez en choisissant une prochaine petite sortie commune.",
    ],
    ["duo", "groupe"],
  ),
  adventure(
    "land-art",
    "Une œuvre éphémère",
    "Composez une forme au sol avec quelques éléments déjà tombés, sans déranger le vivant.",
    30,
    0,
    "exterieur",
    ["creatif", "detente"],
    "Quelques brindilles ou feuilles déjà au sol, dans un lieu où leur manipulation est autorisée.",
    [
      "Choisissez une surface sans végétation fragile et loin du passage.",
      "Disposez des éléments tombés en cercle ou en spirale, sans rien arracher.",
      "Observez votre composition puis redispersez les éléments sur place.",
    ],
  ),
  adventure(
    "marcher-rythme",
    "À chacun son rythme",
    "Variez doucement votre allure sur un trajet plat et familier.",
    30,
    0,
    "exterieur",
    ["mouvement"],
    "Chaussures adaptées, eau et parcours sûr compatible avec votre mobilité.",
    [
      "Commencez par cinq minutes à votre allure habituelle.",
      "Alternez une minute un peu plus vive et deux minutes tranquilles, sans forcer.",
      "Terminez lentement et arrêtez-vous si vous ressentez une gêne.",
    ],
  ),
  adventure(
    "carnet-quartier",
    "Le guide de votre coin",
    "Créez votre propre guide d’un petit morceau de quartier à partir de ce que vous observez.",
    120,
    0,
    "exterieur",
    ["decouverte", "creatif", "mouvement"],
    "Un carnet, un stylo, des chaussures adaptées et de l’eau.",
    [
      "Choisissez un périmètre proche et une durée de retour.",
      "Repérez cinq détails depuis l’espace public et faites des croquis.",
      "Composez une page de guide avec vos observations, sans supposer d’horaires ou d’accès.",
    ],
  ),
  adventure(
    "aquarelle",
    "Trois couleurs seulement",
    "Peignez un petit paysage imaginaire avec une palette volontairement limitée.",
    60,
    15,
    "interieur",
    ["creatif", "detente"],
    "Papier épais, trois couleurs d’aquarelle, pinceau et eau ; estimation de 15 € si le matériel manque.",
    [
      "Choisissez trois couleurs et faites quelques mélanges sur un coin de feuille.",
      "Peignez de grandes formes pour le ciel et le sol.",
      "Ajoutez quelques détails une fois le papier sec.",
    ],
  ),
  adventure(
    "argile",
    "Un vide-poche à modeler",
    "Modelez à la main un petit objet pour accueillir vos clés.",
    60,
    15,
    "interieur",
    ["creatif", "detente"],
    "Argile autodurcissante et protection pour la table ; estimation de 15 €, séchage ultérieur selon le produit.",
    [
      "Protégez la table et formez une petite boule d’argile.",
      "Creusez le centre avec les pouces et lissez les bords.",
      "Ajoutez un motif et laissez sécher selon la notice ; l’objet n’est pas destiné aux aliments.",
    ],
  ),
  adventure(
    "carnet-relie",
    "Un carnet fait main",
    "Assemblez quelques feuilles en un carnet pour vos prochaines idées.",
    60,
    5,
    "interieur",
    ["creatif"],
    "Feuilles, carton fin, perforatrice et ficelle ; environ 5 € si des fournitures manquent.",
    [
      "Pliez les feuilles et le carton au même format.",
      "Perforez près du pli puis attachez avec une ficelle sans trop serrer.",
      "Décorez la couverture et écrivez votre première idée.",
    ],
  ),
  adventure(
    "jeux-papier",
    "Le tournoi sur papier",
    "Organisez quelques manches de jeux faciles à dessiner.",
    60,
    0,
    "interieur",
    ["creatif", "decouverte"],
    "Papier et stylos pour chaque personne.",
    [
      "Tracez une grille de morpion et jouez quelques manches.",
      "Passez à un dessin à deviner en trente secondes chacun votre tour.",
      "Inventez ensemble une variante et testez-la.",
    ],
    ["duo", "groupe"],
  ),
  adventure(
    "menu-voyage",
    "Un repas, une destination",
    "Composez un repas inspiré d’un souvenir de voyage ou d’une recette familiale connue.",
    120,
    15,
    "interieur",
    ["gourmand", "decouverte"],
    "Une recette déjà connue, ses ingrédients adaptés aux allergies et le matériel de cuisine associé ; estimation de 15 € par personne.",
    [
      "Choisissez une recette compatible avec vos équipements et le temps disponible.",
      "Préparez les ingrédients puis cuisinez en suivant votre recette habituelle.",
      "Dressez la table et racontez le souvenir lié au plat.",
    ],
  ),
  adventure(
    "atelier-saveurs",
    "La table des saveurs",
    "Organisez une petite dégustation de produits que vous avez choisis et comparés.",
    60,
    15,
    "interieur",
    ["gourmand", "decouverte"],
    "Trois petites portions de produits comparables, assiettes et papier ; estimation de 15 € par personne, allergies à vérifier.",
    [
      "Choisissez une famille de produits et vérifiez les ingrédients.",
      "Servez de petites portions identifiées et notez les textures, arômes et goûts.",
      "Comparez les impressions sans chercher une bonne réponse.",
    ],
    ["duo", "groupe"],
  ),
  adventure(
    "capsule",
    "La capsule du présent",
    "Rassemblez quelques traces de votre quotidien dans une boîte à rouvrir plus tard.",
    60,
    0,
    "interieur",
    ["creatif", "detente"],
    "Une boîte réutilisée, papier, stylo et petits souvenirs personnels sans valeur sensible.",
    [
      "Choisissez trois petits objets ou dessins qui représentent votre présent.",
      "Ajoutez une lettre et une liste de vos envies.",
      "Fermez la boîte, inscrivez une date de réouverture et gardez-la chez vous.",
    ],
  ),
];

export const activityById = new Map(
  activities.map((activity) => [activity.id, activity]),
);
